### ISSUE TITLE
LocalTime.now() yields invalid time.

### ISSUE THREAD

**Issue by objektwerks** [ekrich/sjavatime#46]
For instance, println(s"*** Local Time: ${LocalTime.now().toString}") yields an invalid time.

**Comment by ekrich** [comment]
@objektwerks Not sure the solution I have would work for you. It still doesn't match Scala.js or JVM which returns a real local time. I am not sure the best path forward yet - time zone offset is needed.

**Comment by ekrich** [comment]
Version 1.1.8 now supports LocalTime. https://github.com/ekrich/sjavatime/pull/65
